### ISSUE TITLE
ArgumentCountError from line 180 of HookRegistry.php: Too few arguments to function SCI\HookRegistry::onDataTypeInit()

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticCite#115]
**Setup**
Product | Version
-- | --
MediaWiki | 1.35.11 (9891838)22:58, 25 July 2023
PHP | 7.4.33 (apache2handler)
MariaDB | 10.5.19-MariaDB-0+deb11u2
Semantic MediaWiki | 4.1.2 (34c5806)

**Issue**
Semantic Cite no longer works with SMW 4.1.2. After upgrading to SMW 4.1.2 the following error is shown:

```
[7fe53c4393abcc686550a091] /wiki/Accueil ArgumentCountError from line 180 of /../w/extensions/SemanticCite/src/HookRegistry.php: Too few arguments to function SCI\HookRegistry::onDataTypeInit(), 0 passed in /../w/includes/HookContainer/HookContainer.php on line 329 and exactly 1 expected
```
**Backtrace:**
```
#0 /../w/includes/HookContainer/HookContainer.php(329): SCI\HookRegistry->onDataTypeInit()
#1 /../w/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#2 /../w/extensions/SemanticMediaWiki/src/DataTypeRegistry.php(515): MediaWiki\HookContainer\HookContainer->run()
#3 /../w/extensions/SemanticMediaWiki/src/DataTypeRegistry.php(130): SMW\DataTypeRegistry->initDatatypes()
#4 /../w/extensions/SemanticMediaWiki/src/PropertyRegistry.php(91): SMW\DataTypeRegistry::getInstance()
#5 /../w/extensions/SemanticMediaWiki/includes/dataitems/SMW_DI_Property.php(98): SMW\PropertyRegistry::getInstance()
#6 /../w/extensions/SemanticMediaWiki/src/Protection/ProtectionValidator.php(328): SMW\DIProperty->__construct()
#7 /../w/extensions/SemanticMediaWiki/src/Protection/ProtectionValidator.php(193): SMW\Protection\ProtectionValidator->checkProtection()
#8 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Permission/TitlePermissions.php(110): SMW\Protection\ProtectionValidator->hasEditProtectionOnNamespace()
#9 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Permission/TitlePermissions.php(64): SMW\MediaWiki\Permission\TitlePermissions->hasUserPermission()
#10 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks/TitleQuickPermissions.php(58): SMW\MediaWiki\Permission\TitlePermissions->checkPermissionFor()
#11 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Hooks.php(1197): SMW\MediaWiki\Hooks\TitleQuickPermissions->process()
#12 /../w/includes/HookContainer/HookContainer.php(329): SMW\MediaWiki\Hooks->onTitleQuickPermissions()
#13 /../w/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#14 /../w/includes/HookContainer/HookRunner.php(4019): MediaWiki\HookContainer\HookContainer->run()
#15 /../w/includes/Permissions/PermissionManager.php(753): MediaWiki\HookContainer\HookRunner->onTitleQuickPermissions()
#16 /../w/includes/Permissions/PermissionManager.php(409): MediaWiki\Permissions\PermissionManager->checkQuickPermissions()
#17 /../w/includes/Permissions/PermissionManager.php(243): MediaWiki\Permissions\PermissionManager->getPermissionErrorsInternal()
#18 /../w/includes/Permissions/PermissionManager.php(262): MediaWiki\Permissions\PermissionManager->userCan()
#19 /../w/includes/page/Article.php(682): MediaWiki\Permissions\PermissionManager->quickUserCan()
#20 /../w/includes/actions/ViewAction.php(80): Article->view()
#21 /../w/includes/MediaWiki.php(531): ViewAction->show()
#22 /../w/includes/MediaWiki.php(313): MediaWiki->performAction()
#23 /../w/includes/MediaWiki.php(947): MediaWiki->performRequest()
#24 /../w/includes/MediaWiki.php(547): MediaWiki->main()
#25 /../w/index.php(53): MediaWiki->run()
#26 /../w/index.php(46): wfIndexMain()
#27 {main}
```

**Comment by jeffw16** [comment]
Can reproduce this

**Comment by krabina** [comment]
We have a [PR](https://github.com/SemanticMediaWiki/SemanticCite/pulls) out that should make SC compatible with 1.39 and 4.1.2

**Comment by krabina** [comment]
PR is integrated. Can you try latest master and see it the problem is still there?
